name: NewXBedwars
version: ${project.version}
main: cc.i9mc.xbedwars.XBedwars
authors: [JinVan]
depend: [NametagEdit, Vault, Nick, DanSync, GlobalPrefix, PluginChannel, Rejoin, GameUtils, WatchNMSLReport]
commands:
  start:
  game: